name: shiver
channels:
  - conda-forge
  - mantid
  - oncat
  - neutrons
dependencies:
  - python>=3.10.14
  - anaconda-client
  - boa
  - conda-build
  - conda-verify
  - check-wheel-contents
  - mantidworkbench
  - pre-commit
  - versioningit
  - pylint
  - pytest
  - pytest-qt
  - pytest-cov
  - setuptools
  - sphinx
  - sphinx-rtd-theme
  - python-build
  - pyoncat
  - pyoncatqt
  - gtk3
  - libstdcxx-ng
