name: shiver
channels:
  - conda-forge
  - mantid
  - oncat
  - neutrons
dependencies:
  - anaconda-client
  - boa
  - conda-build
  - conda-verify
  - check-wheel-contents
  - mantidworkbench
  - pre-commit
  - versioningit
  - pylint=2.17.3
  - pytest=7.2.1
  - pytest-qt=4.2.0
  - pytest-cov=4.0.0
  - qtpy!=2.4.2
  - setuptools
  - sphinx
  - sphinx-rtd-theme
  - python-build
  - pyoncat
  - pyoncatqt
  - gtk3
  - libstdcxx-ng
