name: shiver
channels:
 - conda-forge
 - mantid/label/nightly
dependencies:
 - mantidworkbench
 - pre-commit
 - versioningit
 - pylint=2.17.3
 - pytest=7.2.1
 - pytest-qt=4.2.0
 - pytest-cov=4.0.0
 - sphinx
 - pip
 - pip:
   - https://oncat.ornl.gov/packages/pyoncat-1.4.1-py3-none-any.whl
   - sphinx-rtd-theme
