[project]
name = "shiver"
description = "Spectroscopy Histogram Visualizer for Event Reduction"
dynamic = ["version", "readme","scripts","license"]
requires-python = ">=3.8"
dependencies = [
    "mantidworkbench >= 6.6.20230517",
    "pyoncat == 1.4.1"
]

[build-system]
requires = [
  "setuptools",
   "wheel",
   "toml",
   "versioningit"
]
build-backend = "setuptools.build_meta"

[tool.versioningit.vcs]
method = "git"
default-tag = "0.0.1"

[tool.versioningit.write]
file = "src/shiver/_version.py"

[tool.setuptools.packages.find]
where = ["src"]

[project.gui-scripts]
shiver = "shiver:main"

[tool.pylint]
max-line-length = 120
disable = ["too-many-locals",
           "too-many-statements",
           "too-many-instance-attributes",
           "too-many-arguments",
           "duplicate-code"
]
extension-pkg-whitelist = ["PyQt5"]
