-# load information from pyproject.toml through poetry
{% set pyproject = load_file_data('pyproject.toml') %}
{% set poetry = pyproject.get('tool', {}).get('poetry') %}
{% set description = poetry.get('description') %}
{% set url = poetry.get('repository') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set git_describe_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}


package:
  name: shiver
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  linux-64: python
  number: {{ git_describe_number }}
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit

  build:
    - setuptools
    - versioningit

  run:
    - mantidworkbench

about:
  home: {{ url }}
  license_family: GPL
  license_file: ../LICENSE
  summary: {{ description }}
