name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next]
    tags: ['v*']

jobs:
  tests:
    name: Testing Suite
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.10
      with:
        pixi-version: v0.48.2

    - name: pylint
      run: pixi run pre-commit run -a pylint

    - name: Install shiver
      run: pixi run python -m pip install -e .

    - name: Run tests
      run: pixi run xvfb-run --server-args="-screen 0 1920x1080x24" -a python -m pytest --cov=src --cov-report=xml --cov-report=term

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  Conda-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2

      - name: Build Conda package
        run: pixi run build-conda

      - name: upload conda package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-conda-package
          path: shiver-*.conda

  Conda-verify:
    needs: Conda-build
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test
          init-shell: bash
          create-args: >-
            python=3.10

      - name: Download conda package artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-conda-package
          path: /tmp/local-channel/linux-64

      - name: Get artifact file name
        id: get_filename
        run: |
          echo "Files downloaded:"
          ls /tmp/local-channel/linux-64
          # Get the first file
          FILE_NAME=$(ls /tmp/local-channel/linux-64/*.conda | head -n 1)
          echo "Found file: $FILE_NAME"
          # Save to GitHub Actions output
          echo "conda_file=$FILE_NAME" >> "$GITHUB_OUTPUT"

      - name: Install the package
        run: |
          micromamba install --yes -c conda-forge conda-build conda-index
          python -m conda_index /tmp/local-channel/
          echo "Installation of ${{ steps.get_filename.outputs.conda_file }}"
          micromamba install -c /tmp/local-channel -c conda-forge -c mantid-ornl -c mantid -c neutrons -c oncat --override-channels shiver
      - name: Verify the installation
        env:
          MPLBACKEND: Agg
        run: |
          python -c "import shiver"
          echo " -- Shiver Version -- "
          shiver --version

  Publish:
    runs-on: ubuntu-22.04
    needs: [tests, Conda-verify]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2

      - name: Download previous conda package artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-conda-package

      - name: Get artifact conda package filename
        run: |
          echo "Files downloaded:"
          ls
          # Get the first file
          FILE_NAME=$(ls ./shiver-*.conda)
          echo "Conda package file to publish: $FILE_NAME"

      - name: Upload package to anaconda
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          IS_RC: ${{ contains(github.ref, 'rc') }}
        run: |
          # label is main or rc depending on the tag-name
          CONDA_LABEL="main"
          if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
          echo pushing ${{ github.ref }} with label $CONDA_LABEL
          pixi run anaconda upload --label $CONDA_LABEL --user neutrons ./shiver-*.conda

  # trigger-deploy:
  #   runs-on: ubuntu-22.04
  #   needs: [tests, conda-build]
  #   # only trigger deploys from protected branches and tags
  #   if: ${{ github.ref_protected || github.ref_type == 'tag' }}
  #   steps:
  #     - name: Determine Environment
  #       uses: neutrons/branch-mapper@v2
  #       id: conda_env_name
  #       with:
  #         prefix: shiver

  #     - name: Trigger deploy
  #       id: trigger
  #       uses: eic/trigger-gitlab-ci@v2
  #       with:
  #         url: https://code.ornl.gov
  #         token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
  #         project_id: 7835
  #         ref_name: main
  #         variables: |
  #           PLAY="update"
  #           CONDA_ENV="${{ steps.conda_env_name.outputs.name }}"

  #     - name: Annotate commit
  #       uses: peter-evans/commit-comment@v2
  #       with:
  #         body: |
  #           GitLab pipeline for ${{ steps.conda_env_name.outputs.name }} has been submitted for this commit: ${{ steps.trigger.outputs.web_url }}
