name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next]
    tags: ['v*']

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
    - name: pylint
      run: pre-commit run -a pylint
    - name: Install shiver
      run: python -m pip install -e .
    - name: Run tests
      run: xvfb-run --server-args="-screen 0 1920x1080x24" -a python -m pytest --cov=src --cov-report=xml --cov-report=term
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

  conda-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        condarc: |
          channels:
            - conda-forge
            - mantid/label/nightly
            - oncat
    - name: Build python wheel
      run: |
        python -m build --wheel --no-isolation
        check-wheel-contents dist/shiver-*.whl
    - name: Build conda library
      shell: bash -l {0}
      run: |
        # set up environment
        cd conda.recipe
        echo "versioningit $(versioningit ../)"
        # build the package
        VERSION=$(versioningit ../) conda mambabuild --output-folder . .
        conda verify noarch/shiver*.tar.bz2
    - name: Deploy to Anaconda
      shell: bash -l {0}
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        IS_RC: ${{ contains(github.ref, 'rc') }}
      run: |
        # label is main or rc depending on the tag-name
        CONDA_LABEL="main"
        if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
        echo pushing ${{ github.ref }} with label $CONDA_LABEL
        anaconda upload --label $CONDA_LABEL conda.recipe/noarch/shiver*.tar.bz2

  trigger-deploy:
    runs-on: ubuntu-22.04
    needs: [tests, conda-build]
    # only trigger deploys from protected branches and tags
    if: ${{ github.ref_protected || github.ref_type == 'tag' }}
    steps:
      - name: Determine Environment
        uses: neutrons/branch-mapper@v2
        id: conda_env_name
        with:
          prefix: shiver

      - name: Trigger deploy
        id: trigger
        uses: eic/trigger-gitlab-ci@v2
        with:
          url: https://code.ornl.gov
          token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          project_id: 7835
          ref_name: main
          variables: |
            PLAY="update"
            CONDA_ENV="${{ steps.conda_env_name.outputs.name }}"

      - name: Annotate commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            GitLab pipeline for ${{ steps.conda_env_name.outputs.name }} has been submitted for this commit: ${{ steps.trigger.outputs.web_url }}
