name: CI

on:
  pull_request:
  push:
    branches: [main, qa, next]

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        mamba-version: "*"
        environment-file: environment.yml
    - name: pylint
      run: pre-commit run -a pylint
    - name: Install shiver
      run: python -m pip install -e .
    - name: Run tests
      run: xvfb-run --server-args="-screen 0 1920x1080x24" -a python -m pytest --cov=src --cov-report=xml --cov-report=term
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
