name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next]
    tags: ['v*']

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.10
      with:
        pixi-version: v0.48.2
    - name: pylint
      run: pre-commit run -a pylint
    - name: Install shiver
      run: python -m pip install -e .
    - name: Run tests
      run: xvfb-run --server-args="-screen 0 1920x1080x24" -a python -m pytest --cov=src --cov-report=xml --cov-report=term
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  package:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2

      - name: Build Conda package
        run: pixi run conda-build

      - name: upload conda package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-conda-package
          path: shiver-*.conda

  conda-verify:
    needs: tests
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test
          init-shell: bash
          create-args: >-
            python=3.10

      - name: Download conda package artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-conda-package
          path: /tmp/local-channel/linux-64

      - name: Install the package
        run: |
          micromamba install --yes -c conda-forge conda-build conda-index
          python -m conda_index /tmp/local-channel
          micromamba install --yes -c /tmp/local-channel -c mantid-ornl -c conda-forge shiver

      - name: Verify the installation
        run: python -c "import shiver"

  # trigger-deploy:
  #   runs-on: ubuntu-22.04
  #   needs: [tests, conda-build]
  #   # only trigger deploys from protected branches and tags
  #   if: ${{ github.ref_protected || github.ref_type == 'tag' }}
  #   steps:
  #     - name: Determine Environment
  #       uses: neutrons/branch-mapper@v2
  #       id: conda_env_name
  #       with:
  #         prefix: shiver

  #     - name: Trigger deploy
  #       id: trigger
  #       uses: eic/trigger-gitlab-ci@v2
  #       with:
  #         url: https://code.ornl.gov
  #         token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
  #         project_id: 7835
  #         ref_name: main
  #         variables: |
  #           PLAY="update"
  #           CONDA_ENV="${{ steps.conda_env_name.outputs.name }}"

  #     - name: Annotate commit
  #       uses: peter-evans/commit-comment@v2
  #       with:
  #         body: |
  #           GitLab pipeline for ${{ steps.conda_env_name.outputs.name }} has been submitted for this commit: ${{ steps.trigger.outputs.web_url }}
